### ISSUE TITLE
Disabled cards can be dragged 

### ISSUE THREAD

**Issue by SamuelRott** [oskarrough/slaytheweb#101]
Currently when a card cost more energy then you have you can drag it and it get stuck over the player or the monster you targeted.
<img width="1278" alt="Screen Shot 2020-08-19 at 10 26 06" src="https://user-images.githubusercontent.com/12135011/90611012-7a6f0a00-e206-11ea-8ca5-b62f53b2b44a.png">

The expected behaviour would be => when a card cost more energy then you currently have you shouldn't be able to drag it.

**Comment by oskarrough** [comment]
If you don't have enough energy to play a card, we could either

a) complete disable dragdrop
b) allow you to drag it just a little bit but then "abort" the drag and animate it back into your hand

b sounds the nicest?

**Comment by SamuelRott** [comment]
B is the nicest and it could reusable for other scenario like "you are not allowed to target this player/monster with this card"

**Comment by oskarrough** [comment]
OK let's go for that! Here's an idea:

in `onDrag` you check if the dragged card element has the `disabled` attribute. The element is available under `this.target` inside `onDrag` because of gsap.

If so, cancel the drag https://greensock.com/docs/v3/Plugins/Draggable/endDrag() and animate back into the hand. You can reuse this https://github.com/oskarrough/slaytheweb/blob/master/public/ui/dragdrop.js#L40

**Comment by oskarrough** [comment]
Closed by #105
